name = "GlobalGrids"
uuid = "04ffc4db-dae8-4dbd-80c0-66bcb7ba3f11"
version = "1.0.0-DEV"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
H3_jll = "60c8821e-da38-5dbd-93c7-983f1e6d69be"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"

[extensions]
GlobalGridsMakieExt = ["Makie"]
GlobalGridsRastersExt = ["Rasters"]

[compat]
Extents = "0.1.6"
GeoFormatTypes = "0.4.4"
GeoInterface = "1.6.0"
GeometryBasics = "0.5.10"
GeometryOps = "0.1.30"
H3_jll = "4.2.1"
LinearAlgebra = "1.12.0"
Makie = "0.24"
Proj = "1.9.0"
Rotations = "1.7.1"
StaticArrays = "1.9.15"
StaticArraysCore = "1.4.4"
StyledStrings = "1.11.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
