project:
  type: book

engines: ['julia']

book:
  title: "GlobalGrids.jl"
  # author: "Josh Day and contributors"
  chapters:
    - index.qmd
    - h3.qmd
    - coordinates.qmd
    - icosahedron.qmd
    # - api.qmd

# bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
