project:
  type: website
  render:
    - "*.qmd"
engines: ['julia']
website:
  title: "GlobalGrids.jl"
  page-navigation: true
  navbar:
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/joshday/GlobalGrids.jl
        aria-label: GitHub
  sidebar:
    contents:
      - index.qmd
      - h3.qmd
      - coordinates.qmd
      - icosahedron.qmd

format:
  html:
    theme: cosmo
    toc: true
